# .github/workflows/test_coverage.yml

name: "Run Test Case"

# PR 생성시에만 해당 워크플로우를 실행해요
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: 노드 설치
        uses: actions/setup-node@v3
        with:
          node-version: "20.12.0"
      - name: pnpm 설치
        run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm test -- --reporter=junit --outputFile=vitest-report.xml
      - run: pnpm coverage -- package/**/*.test.ts
      - name: 테스트 커버리지 결과 PR에 코멘트 추가하기
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.PR_WRITE_TOKEN }}
